#!/bin/sh

while getopts "i:o:t:c" opt; do
	case $opt in
	i) inpfile=$OPTARG;;
	o) outfile=$OPTARG;;
	t) tmac=$OPTARG;;
	c) content=1;;
	esac
done

if [ -z "$inpfile" -o -z "$outfile" -o -z "$tmac" ]; then
	echo "Usage: smldoc [-c] <-t TMAC_FILE> <-i INPUT_FILE> <-o OUTPUT_FILE>"
	exit 1
fi

dir=$(dirname $0)
tmpdir=$(mktemp -d /tmp/smldoc.XXX)
coverpage=$(mktemp ${tmpdir}/${inpfile##*/}.cover.XXX)
tocfile=$(mktemp ${tmpdir}/${inpfile##*/}.toc.XXXXXX)
document=$(mktemp ${tmpdir}/${inpfile##*/}.doc.XXX)

mkdir -p $tmpdir
touch $outfile
cat $inpfile | awk -v covpage=$coverpage -f ${dir}/parser >$document
echo ".content" >$tocfile

while [ "$(md5sum $outfile | cut -d ' ' -f 1)" != "$md5" ]; do
	tocfile2=$(mktemp ${tmpdir}/${inpfile##*/}.toc.XXXXXX)
	md5=$(md5sum $outfile | cut -d ' ' -f 1)

	echo ".bp" >>$tocfile
	echo ".content" >$tocfile2

	if [ ${content:=0} -eq 0 ]; then
		tocfile=
	fi

	cat $tmac $tocfile $document | preconv | groff -Tps -e 1>$outfile 2>>$tocfile2

	if [ -n "$(grep -v '^\.content' $tocfile2)" ]; then
		err="$(grep -v '^\.content' $tocfile2)"
		toc="$(cat $tocfile2)"

		echo "$toc" | grep '^\.content' >$tocfile2
	fi

	tocfile=$tocfile2
done

if [ -n "$err" ]; then
	echo "$err" 1>&2
fi

rm -rf $tmpdir
