#!/bin/sh

while getopts "i:o:t:c" opt; do
	case $opt in
	i) inpfile=$OPTARG;;
	o) outfile=$OPTARG;;
	t) tmac=$OPTARG;;
	c) content=1;;
	esac
done

if [ -z "$inpfile" -o -z "$outfile" -o -z "$tmac" ]; then
	echo "Usage: noname [-c] <-t TMAC_FILE> <-i INPUT_FILE> <-o OUTPUT_FILE>"
	exit 1
fi

dir=$(dirname $0)
tmpdir=$(mktemp -d /tmp/smldoc.XXX)
tmpfile=$(mktemp ${tmpdir}/${inpfile##*/}.tmp.XXX)
tocfile=$(mktemp ${tmpdir}/${inpfile##*/}.toc.XXXXXX)

mkdir -p $tmpdir
touch $outfile
cat $inpfile | ${dir}/parser >$tmpfile
echo ".content" >$tocfile

if [ ${content:=0} -eq 0 ]; then
	cat $tmac $tmpfile | preconv | groff -Tps -e >$outfile 2>/dev/null
	rm -rf $tmpdir
	exit
fi

while [ "$(md5sum $outfile | cut -d ' ' -f 1)" != "$md5" ]; do
	tocfile2=$(mktemp ${tmpdir}/${inpfile##*/}.toc.XXXXXX)
	md5=$(md5sum $outfile | cut -d ' ' -f 1)

	echo ".bp" >>$tocfile
	echo ".content" >$tocfile2

	cat $tmac $tocfile $tmpfile | preconv | groff -Tps -e >$outfile 2>>$tocfile2

	tocfile=$tocfile2
done

rm -rf $tmpdir
